### ISSUE TITLE
Color/theme distortion after adding new machine

### ISSUE THREAD

**Issue by oktay454** [kalaksi/lightkeeper#5] opened 2023-09-18 08:25 UTC
Color/theme distortion after adding new machine
![image](https://github.com/kalaksi/lightkeeper/assets/1449620/b456f721-a567-4da2-b33f-f6adc4d12fee)
![image](https://github.com/kalaksi/lightkeeper/assets/1449620/cd3b6163-d7c9-41fc-a9f8-abf082b6b58e)
![image](https://github.com/kalaksi/lightkeeper/assets/1449620/68955ca3-adcb-4eb4-965c-232cc4ac0607)

**Comment by mbnoimi** [comment] 2023-09-18 13:12
Same issue here. I'm unable to use it at all!

![image](https://github.com/kalaksi/lightkeeper/assets/284547/0d7183d4-0106-4c55-866f-8db70709e490)

**Comment by kalaksi** [comment] 2023-09-18 14:23
Thanks for the screenshots. I have now managed to reproduce the issue. I'll have to lock down the theme properly so it won't change on different systems (maybe later there will be proper support for e.g. light theme).

I'll be fixing this soon.

**Comment by kalaksi** [comment] 2023-09-19 19:47
That took more work than I expected. Since this was a major issue, I'm immediately publishing version 0.5.1 which is now building.

**Comment by kalaksi** [comment] 2023-09-22 16:18
Did the update resolve your issues?

**Comment by oktay454** [comment] 2023-09-25 14:01
Sorry for replying late.
It was a very busy week.
While 2 SSH keys were visible in the ssh-add -l output, when I ran Lightkeeper and wanted to connect, it provided a smooth connection.

**Comment by oktay454** [comment] 2023-09-25 14:05
Not work. Özellikle yeni bir makine eklendiğinde oluyor. Pencere anlık olarak kapanıp açılıyor ve böyle oluyor.
![resim](https://github.com/kalaksi/lightkeeper/assets/1449620/e8ec4a09-b284-4ebc-925e-84595cd3acb8)

**Comment by kalaksi** [comment] 2023-09-25 14:33
Hmm, yes, it breaks for me too if I add a host. Does it look good to you before Lightkeeper does a restart?

**Comment by kalaksi** [comment] 2023-10-01 08:42
Configuration can now be reloaded without a full app reload, so this shouldn't be an issue anymore.

**Comment by oktay454** [comment] 2023-10-01 19:21
Let me point out one more small situation.
I am using version 0.6.2. There is no color/theme problem. However, active connections are terminated. There is no problem with one or two machines, but as the number of managed machines increases, opening closed connections will negatively affect the comfort of use.

**Comment by b1ek** [comment] 2023-10-19 08:28
> I have now managed to reproduce the issue

Can you please publish the steps to reproduce?

**Comment by kalaksi** [comment] 2023-10-19 21:03
To be clear, this isn't a problem anymore and I'm going to close this issue, but here are the steps:

1. Use light theme in your desktop environment
2. Change QML styling to "Default" (if I remember right) with qtquick_style setting in config (or an environment variable used by Qt). 
3. Add a host. At thispoint Lightkeeper used to do a restart/reload which somehow breaks the enforcing of theme settings and that's why you'd get the light "Default" theme, which is unusable and currently not supported.

**Closed by kalaksi** 2023-10-19 21:03 UTC
